### ISSUE TITLE
Can't detect `--`

### ISSUE THREAD

**Issue by cloudhead** [blyxxyz/lexopt#21]
I'd like to pass everything after `--` to another command, but can't seem to detect the `--`. For instance, this test fails:

```rust

#[test]
fn test_lexopt() {
    let mut p = lexopt::Parser::from_args(&["foo", "bar", "--", "baz"]);
    assert_eq!(
        p.next().unwrap(),
        Some(lexopt::Arg::Value(std::ffi::OsString::from("foo")))
    );
    assert_eq!(
        p.next().unwrap(),
        Some(lexopt::Arg::Value(std::ffi::OsString::from("bar")))
    );
    assert_eq!(
        p.next().unwrap(),
        Some(lexopt::Arg::Value(std::ffi::OsString::from("--")))
    );
}
```
```
thread 'test_lexopt' panicked:
assertion `left == right` failed
  left: Some(Value("baz"))
 right: Some(Value("--"))
```
How would I get all the arguments after `--`? Or break out of the parsing loop once `--` is encountered, without parsing `baz`?

**Comment by blyxxyz** [comment]
lexopt treats `--` as a marker that says no more options are coming. This is the standard meaning. What you're trying to do may or may not fit with that, I'm not sure. There's probably a workaround one way or another but it depends on the details, particularly on the positional arguments before `--`.

Is there a specific existing program whose style you're imitating?

**Comment by cloudhead** [comment]
Yes, for example `cargo test foo -- --nocapture` would pass `--nocapture` to the underlying test binary, but `test foo` to `cargo`.

So this implies a way to know which arguments are before, vs. after the `--`

**Comment by blyxxyz** [comment]
In that case `foo` is actually also passed to the test binary. `cargo test -- foo --nocapture` has the same meaning. All positional arguments are forwarded, and all arguments after `--` are interpreted as positional arguments even if they otherwise look like options.

For example this command:
```console
$ cargo test basic_fuzz --profile=dev -- --nocapture
```
Spawns this process:
```console
$ pgrep -a lexopt
2991115 [...]/lexopt/target/debug/deps/lexopt-bb40919c31e6f7b5 basic_fuzz --nocapture
```

So with lexopt you'd just keep watching for for `Arg::Value`s and build the arguments for the test binary from that.
```rust
fn main() {
    let mut p = lexopt::Parser::from_args(&["foo", "--", "--nocapture"]);
    assert_eq!(
        p.next().unwrap(),
        Some(lexopt::Arg::Value(std::ffi::OsString::from("foo")))
    );
    assert_eq!(
        p.next().unwrap(),
        Some(lexopt::Arg::Value(std::ffi::OsString::from("--nocapture")))
    );
}
```

**Comment by cloudhead** [comment]
Hmm I see, so I basically have to know when I'm done parsing `Value`s in the main process, and pass the rest of the `Value`s to the sub-process.

**Comment by blyxxyz** [comment]
Exactly. If you have a known number of positional arguments you can use the `is_none()` trick:
```rust
Value(value) if arg1.is_none() => arg1 = Some(value),
Value(value) if arg2.is_none() => arg2 = Some(value),
Value(value) => subprocess_args.push(value),
```

**Comment by cloudhead** [comment]
Ok, good enough thanks :+1:

**Comment by mrak** [comment]
I still think it would be convenient for knowing when the `--` has occurred. One example is the `parallel` program from moreutils that has different processing modes depending on where the `--` occurs within the positional arguments:

```
parallel [OPTIONS] command -- arguments
        for each argument, run command with argument, in parallel
parallel [OPTIONS] -- commands
        run specified commands in parallel
```

It would be nice if it were a method on the lexopt parser itself, such as `parser.seen_terminator()` to return a boolean for whether or not `--` has been seen. I think this could fit in well with existing usages without introducing an additional enum value like `lexopt::Arg::Terminator` that would need to be accounted for in match statements. 

```rust
use lexopt::prelude::*;
let mut command = None;
let mut commands = Vec::new();
let mut arguments = Vec::new();
let mut parser = lexopt::Parser::from_env();
while let Some(arg) = parser.next()? {
    match arg {
        Short('h') | Long("help") => {
            usage();
            return;
        }
        // other options...
        Value(val) if command.is_none() && !parser.seen_terminator() => command = Some(val),
        Value(val) if command.is_some() && parser.seen_terminator() => arguments.push(val),
        Value(val) if command.is_none() && parser.seen_terminator() => commands.push(val),
        _ => return Err(arg.unexpected()),
    }
}
```

**Comment by mrak** [comment]
I appreciate the detailed response! I agree that this example has its own bespoke interpretation of `--`. Hopefully others finding this thread via search like I did will find it useful
