### ISSUE TITLE
Retrieve argument count from the Parser

### ISSUE THREAD

**Issue by nordzilla** [blyxxyz/lexopt#4]
There is currently no way to tell the total length of arguments from the `lexopt::Parser`. 

Consider this scenario:

```rust
pub struct Token;

// Clone trait bound is just to prevent conflict with the blanket
// implementation of impl<T> From<T> for T
impl<T: Clone> From<T> for Token {
    fn from(_: T) -> Self {
        Self {}
    }
}

fn lex_tokens() -> Result<Vec<Token>, Error> {
    let mut tokens = Vec::new();
    let mut p = parse("-a -bc value --long");
    while let Some(arg) = p.next()? {
        match arg {
            Short(val) => tokens.push(val.try_into()?),
            Long(val) => tokens.push(val.try_into()?),
            Value(val) => tokens.push(val.try_into()?),
        }
    }
    Ok(tokens)
}
```

It would be convenient if the parser were able to retrieve the argument count before the loop, so that we can initialize the `Vec` with a starting capacity that we know will hold all of the tokens:

```rust
fn lex_tokens() -> Result<Vec<Token>, Error> {
    let mut p = parse("-a -bc value --long");
    let mut tokens = Vec::with_capacity(p.arg_count());
    while let Some(arg) = p.next()? {
        match arg {
            Short(val) => tokens.push(val.try_into()?),
            Long(val) => tokens.push(val.try_into()?),
            Value(val) => tokens.push(val.try_into()?),
        }
    }
    Ok(tokens)
}
```

I don't think there's a workaround for `from_args()`, but with the `from_env()` case, users can just call:

```rust
Vec::with_capacity(std::env::args_os().len())
```
which honestly is not that bad, but it is unfortunate to have to use `std::env::args_os()` outside of the `Parser`.
Of course, there is still no guarantee that all the tokens will fit, even with setting the capacity, since combined short options may produce multiple tokens from the same argument. But it's still nice to get an estimate. 

`arg_count()` could be as simple as 

```rust
pub fn arg_count(&self) -> usize {
   self.source.len()
}
```
But there would be some tradeoffs to consider:

1) `source` would have to become a `dyn ExactSizeIterator`
```rust
source: Box<dyn ExactSizeIterator<Item = OsString> + 'static>,
```

2) `from_args()` would have to ensure that its `IntoIter` type is exact size
```rust
pub fn from_args<I>(args: I) -> Parser
where
    I: IntoIterator + 'static,
    I::Item: Into<OsString>,
    <I as IntoIterator>::IntoIter: ExactSizeIterator,
{
```

3) This would be a breaking change; your `parse()` helper function for your tests would have to collect into something with an exact size first, because a `SplitWhitespace` is lazily evaluated.

```rust
fn parse(args: &'static str) -> Parser {
    Parser::from_args(args.split_whitespace().map(bad_string).collect::<Vec<_>>())
}
```

One benefit of this is that all iterators would be capped out at `usize`'s max value, so overflow would no longer be an issue for the position functionality. 

I will leave it up to you to determine if such a change would be in line with your vision for this project. I'm just trying to think from a perspective of reducing friction for users. Is it more convenient to be able to get the arg count natively from the API, or is it more convenient to parse from iterators of unknown size? I don't know, but I felt like asking the question.

Anyhow, feel free to close this issue if this is not in line with your vision, and at least the decision will be documented here. If you keep the current behavior, it may be worth documenting how to get the size separately from `std::env:args_os()`

**Comment by blyxxyz** [comment]
I think getting the size ahead of time is niche enough to justify the workaround. And it's *probably* easy enough to figure out to not need documenting?

But it could be enabled by making `Parser` generic instead of using `dyn`. I wanted to see if I could get by without it because it'd add usually-unnecessary complexity for users, but it's at least worth experimenting with in a branch.

There could be a function `Parser<T>::inner(&self) -> &T`, and since `from_env()` would return a `Parser<ArgsOs>` that would be enough.

It would be a breaking change, and I don't think this issue alone would be enough to justify it, but it has other benefits, like making it possible to derive `Clone`.

**Comment by nordzilla** [comment]
> I think getting the size ahead of time is niche enough to justify the workaround. And it's probably easy enough to figure out to not need documenting?

That's fair. I am clearly biased by my own use case, which seems to be less common. And I have a tendency to err on the side of over-documentation.

> It would be a breaking change, and I don't think this issue alone would be enough to justify it, but it has other benefits, like making it possible to derive Clone.

Yes, I also agree with this.
