### ISSUE TITLE
Why does `bin_name()` return `str` rather than `OsString`?

### ISSUE THREAD

**Issue by Minoru** [blyxxyz/lexopt#6]
`lexopt` tries not to convert strings unless absolutely necessary, but `bin_name()` deviates from that. The source code doesn't explain why. If `bin_name()` returned `OsString`, that'd be more consistent with other methods.

**Comment by blyxxyz** [comment]
I wrote up some considerations [here](https://github.com/blyxxyz/lexopt/commit/193ef7341ba1df20e7b202e8b08b68c36c9a1068#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L469) but they fell through the gaps the first time I scrapped the method.

The main use case I envisioned for it was to show in help messages and error messages. Try running `/bin/cat --help` and `/bin/cat doesnotexist`: if you have GNU cat then you'll see
```
Usage: /bin/cat [OPTION]... [FILE]...
```
```
/bin/cat: doesnotexist: No such file or directory
```
It does this [based on `argv[0]`](https://github.com/coreutils/coreutils/blob/master/src/cat.c#L571).

It's easy to format a `&str` but hard to format an `&OsStr`. With the current API you can do `println!("Usage: {} blabla", parser.bin_name().unwrap_or("myprog"));`, but if it returned an `&OsStr` you'd have to do more work.

Unlike a normal argument, which might be an actual file you have to open, I don't think there are any common cases where you'd absolutely have to process your own command name even if it's invalid unicode. (It's not even a good way of finding the actual executable.) But then a lossy decode might make more sense than ignoring it.

(I want to remove/overhaul the whole method, as discussed in https://github.com/blyxxyz/lexopt/issues/5#issuecomment-882822658)

**Comment by Minoru** [comment]
Thanks! This answers my question completely, so I'll close the issue.
